name: Deploy Next.js to VPS with GHCR & Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and Push Docker Image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.actor }}/atleticapadrepio
          sudo docker build -t --build-arg database_url="${{ secrets.MONGODB_URI }}" $IMAGE_NAME:latest .
          sudo docker push $IMAGE_NAME:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: SSH into VPS and Deploy Container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            sudo docker login ghcr.io -u $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
            
            cd /home/${{ secrets.VPS_USER }}/atleticapadrepio

            sudo docker-compose pull
            sudo docker-compose down
            sudo docker-compose up -d
